Maven
BME-MIT-IET/iet-hf-2023-nrv pull request #15
Opened 2023-05-25 09:57 UTC by strbikanna

Talán még egy próbát megér. Töröltem az update "dependency graph nevű" optional step-et, mindig annál volt fail. Hátha így jó.

2023-05-25 18:20 UTC, jgbor requested changes
Itt is conflict van, és web editorban meg se tudom nézni, azt írja túl komplex :(

2023-05-26 21:41 UTC, Baleg00 approved these changes

2023-05-27 08:17 UTC, jgbor reviewed
Elvileg megoldottam a conflictokat és működik már

2023-05-27 08:17 UTC, jgbor approved these changes

2023-05-27 08:23 UTC, Baleg00 approved these changes

2023-05-27 08:23 UTC, merged